-- MySQL Script generated by MySQL Workbench
-- Thu Jan 17 21:22:08 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`folder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`folder` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `foldercol` VARCHAR(45) NOT NULL,
  `DateCreated` DATETIME NOT NULL,
  `DateModify` DATETIME NOT NULL,
  `Amount` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`files` (
  `id` INT(11) NOT NULL,
  `ContainerName` VARCHAR(70) NOT NULL,
  `MetaName` VARCHAR(70) NOT NULL,
  `MetaType` VARCHAR(10) NOT NULL,
  `DateCreated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MetaIsImage` TINYINT(1) NOT NULL,
  `MetaSize` INT(20) NOT NULL,
  `folder_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_files_folder_idx` (`folder_id` ASC) VISIBLE,
  CONSTRAINT `fk_files_folder`
    FOREIGN KEY (`folder_id`)
    REFERENCES `mydb`.`folder` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
